pipeline {
    agent any
    tools {
        maven 'Maven363' 
    }
    environment {
        DATE = new Date().format('yy.M')
        TAG = "${DATE}.${BUILD_NUMBER}"
    }
    triggers {
        pollSCM 'H * * * *'
    }
    stages {
        stage('Build') {
            steps {
                echo "Building..."
                sh '''
                mvn clean install -DskipTests
                '''
            }
        }
        stage('Test') {
            steps {
                echo "Testing..."
                sh '''
                mvn test
                '''
            }
        }
        stage('Mutation') {
            steps {
                echo "Mutating..."
                sh '''
                mvn org.pitest:pitest-maven:mutationCoverage
                '''
            }
        }
        stage('Deliver') {
            agent { docker 'gustavoapolinario/jenkins-docker' }
            steps {
                sh'''
                service docker status
                service docker start
                service docker status
                '''
            }
        }
    }
}
