pipeline {
    agent any
    tools {
        maven 'Maven363' 
    }
    environment {
        DATE = new Date().format('yy.M')
        TAG = "${DATE}.${BUILD_NUMBER}"
        DOCKERFILE_PATH = "src/main/docker"
    }
    triggers {
        pollSCM 'H * * * *'
    }
    stages {
        stage('Build') {
            steps {
                echo "Building..."
                sh '''
                mvn clean install -DskipTests
                '''
            }
        }
        stage('Test') {
            steps {
                echo "Testing..."
                sh '''
                mvn test
                '''
            }
        }
        stage('Mutation') {
            steps {
                echo "Mutating..."
                sh '''
                mvn org.pitest:pitest-maven:mutationCoverage
                '''
            }
        }
        stage('Update Version') {
            steps {
                echo "Updating app version..."
                sh '''
                git checkout Main
                python3 update_version.py
                git add .
                git commit -m 'Jenkins Update Version'
                git push
                '''
                withCredentials([usernamePassword(credentialsId: 'GitHubCreds', passwordVariable: 'GIT_PASSWORD', usernameVariable: 'GIT_USERNAME')]) {
                        sh('git push https://${GIT_USERNAME}:${GIT_PASSWORD}@github.com/MatAndreoli/PokemonBack.git')
                }
            }
        }
        stage('Deliver') {
            steps {
                sh'''
                docker build -f $DOCKERFILE_PATH/Dockerfile.jvm -t pokemon-api .
                docker ps -a
                docker rmi pokemon-api
                '''
            }
        }
    }
}
