pipeline {
    agent any
    tools {
        maven 'Maven363' 
    }
    environment {
        DATE = new Date().format('yy.M')
        TAG = "${DATE}.${BUILD_NUMBER}"
    }
    triggers {
        pollSCM '* * * * *'
    }
    stages {
        stage('Build') {
            steps {
                echo "Building..."
                sh '''
                mvn clean install -DskipTests
                '''
            }
        }
        stage('Test') {
            steps {
                echo "Testing..."
                sh '''
                mvn test
                '''
            }
        }
        stage('Mutation') {
            steps {
                echo "Mutating..."
                sh '''
                mvn org.pitest:pitest-maven:mutationCoverage
                '''
            }
        }
        stage('Deliver') {
            steps {
                sh'''
                env | grep DOCKER_
                docker build -f src/main/docker/Dockerfile.jvm -t api-test:${TAG} .
                '''
            }
        }
    }
}
